{{- if .Values.proxy.enabled -}}
{{- $fullName := include "rocketmq.proxy.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName| quote }}
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    {{- include "rocketmq.selectorLabels" . | nindent 4 }}
    component: proxy
{{- end }}